##########################################################################
FROM ros:noetic-ros-core AS ros-base

FROM dev-cpu-runtime
ARG PROXY_HOST=127.0.0.1
ARG PROXY_PORT=50000
SHELL ["/bin/bash", "-c"]
COPY --from=ros-base /opt/ros /opt/ros

### Required packages
RUN sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu/ focal main" > /etc/apt/sources.list.d/ros1-latest.list 

RUN apt-get update && \
    apt-get install -y --no-install-recommends\
    stow ninja-build git software-properties-common wget gnupg2 cmake g++ sudo && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

ADD cartographer /opt/workspace/src/cartographer
ADD cartographer_ros /opt/workspace/src/cartographer_ros
ADD abseil-cpp /opt/workspace/abseil-cpp
WORKDIR /opt/workspace
RUN src/cartographer/scripts/install_abseil.sh

RUN pip3 install rosdep rosinstall \
     -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN HTTP_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     HTTPS_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     ALL_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     http_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     https_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     all_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     rosdep init
RUN HTTP_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     HTTPS_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     ALL_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     http_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     https_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     all_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     rosdep -q update --rosdistro noetic
RUN apt-get update -q && \
     ROS_OS_OVERRIDE=ubuntu:20.04:focal \
     DEBIAN_FRONTEND=noninteractive \
     HTTP_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     HTTPS_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     ALL_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     http_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     https_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     all_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     rosdep -q install --from-paths src --ignore-src --rosdistro noetic -y && \
     rm -rf /var/lib/apt/lists/* && \
     apt-get clean

RUN pip3 install rosdep rosinstall empy defusedxml netifaces pandas seaborn \
     -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN source /opt/ros/noetic/setup.bash && catkin_make_isolated --install --use-ninja

ADD sim2real_ep /opt/ep_ws/src/sim2real_ep
WORKDIR /opt/ep_ws
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
RUN apt-get update && \
     source /opt/workspace/devel_isolated/setup.bash && \
     ROS_OS_OVERRIDE=ubuntu:20.04:focal \
     DEBIAN_FRONTEND=noninteractive \
     HTTP_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     HTTPS_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     ALL_PROXY=http://${PROXY_HOST}:${PROXY_PORT} \
     http_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     https_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     all_proxy=http://${PROXY_HOST}:${PROXY_PORT} \
     rosdep -q install --from-paths src --ignore-src --rosdistro noetic -y && \
     rm -rf /var/lib/apt/lists/* && \
     apt-get clean

RUN source /opt/workspace/devel_isolated/setup.bash && catkin_make install --use-ninja -DSETUPTOOLS_DEB_LAYOUT=OFF